### ISSUE TITLE
compat module

### ISSUE THREAD

**Issue by skuschel** [skuschel/postpic#125]
maybe mokeypatching numpy to provide transparent compatibility for older versions.
This refactors #124

**Comment by skuschel** [comment]
A proof-of-principle how the compat module could monkeypatch numpy functions if needed is implemented in the branch `ku/compatmodule`. See https://gist.github.com/skuschel/b1b176cd57aeca31b3f4b4d554d512a7 for a demonstration of it.

**Comment by Ablinne** [comment]
Monkeypatching seems a bad Idea. Let's just have a compat module without it.

**Comment by Ablinne** [comment]
fixed by merging #127
