### ISSUE TITLE
Give meaningful error message when extent is out of bounds

### ISSUE THREAD

**Issue by stetie** [skuschel/postpic#148]
When reconstructing the kspace from a given simulation dump, e.g.
```python
dump = pp.readDump(file)
dump.kspace_Ex(extent=(-0.1e-4, 0.2e-4, 2.0e-5, 8.0e-5))
```
the user can set an extent to cutout from the original fields. I accidentally set the new extent in such a way that it exceeded the original one. I got the following error message:
https://gist.github.com/stetie/03a5a436e259c00e3bae16145fc51c36
A more meaningful error message would have saved a lot of work.

**Comment by Ablinne** [comment]
@stetie could you check if my patch #149 solves this issue for you?

**Comment by stetie** [comment]
Yes, this solves the issue.

**Comment by Ablinne** [comment]
Thanks, I'll merge it as soon as the integration tests are finished.
