### ISSUE TITLE
Crash because `Field.transformed_axes_origins` gets promoted to np.ndarray

### ISSUE THREAD

**Issue by Ablinne** [skuschel/postpic#166]
At some point, ```Field.transformed_axes_origins```, which should be a list, gets promoted to np.ndarray. This can lead to crashes.

```
ValueError                                Traceback (most recent call last)
<ipython-input-91-ae914e8a2c36> in <module>()
      1 fig, ax = plt.subplots()
----> 2 field_imshow(abs(a20k).mean(2), ax)
      3 #abs(a20k - a20k_alt).matrix

/raid/home/albn/.local/lib/python3.5/site-packages/postpic/datahandling.py in new_method(self, axis, out, keepdims, **kwargs)
    382                 for i in reversed(sorted(axisiter)):
    383                     del axes[i]
--> 384                     del tao[i]
    385                     del ats[i]
    386 

ValueError: cannot delete array elements
```

**Comment by Ablinne** [comment]
The field in question has been exported to `.npz` and loaded using `Field.loadfrom`. My guess is that `Field._transformed_axes_origins` is stored as an `np.ndarray` on export, but not converted back to a list on `loading`. @stetie  I will assign this to you as you have written the `io` code.

**Comment by Ablinne** [comment]
Seems I can't assign to you because you are not a member of this repo...

**Comment by Ablinne** [comment]
The same problem applies to `Field.axes_transform_state`.

**Comment by stetie** [comment]
That's why I don't like untyped programming languages...
