### ISSUE TITLE
Field.integrate sanity checks missing

### ISSUE THREAD

**Issue by skuschel** [skuschel/postpic#189]
if using the method 'constant' or 'fast', the grid MUST be equidistant. Otherwise the method will give wrong results.
Todos:
1) This sanity check is missing. Add sanity check.
2) Add more test cases to detect this bug.

**Comment by Ablinne** [comment]
This is not true. What those functions compute is effectively a Riemann sum, which can also be applied to non-equidistant grids. That's why both functions take care to weight every data point by the size of its grid cell.

**Comment by skuschel** [comment]
oh! I overlooked the the slice markers `:`. I still added some test cases in my dev branch and also added an TypeError if someone tries to modify the extent of a non-linear grid.
