### ISSUE TITLE
add mean and variance functions to particles.py

### ISSUE THREAD

**Issue by skuschel** [skuschel/postpic#19]
add `mean(self, func)` and `var(self, func)` to https://github.com/skuschel/postpic/blob/master/postpic/analyzer/particles.py#L559 such that mean and variance can be calculated from any per-particle-propery taking the weight into account. What elese to add here? `median` and `quantile` maybe?
- [x] mean
- [x] var
- [x] median
- [x] quantile
- [x] add tests/example
- [x] add documentation

**Comment by skuschel** [comment]
mean and var added 9b2387ff

**Comment by skuschel** [comment]
median an quantile added cb590328

**Comment by Ablinne** [comment]
@skuschel, as this is mostly done, shouldn't we close this for v0.4?
