### ISSUE TITLE
k-space reconstruction

### ISSUE THREAD

**Issue by skuschel** [skuschel/postpic#2]
There are routines needed to reconstruct the k-space from the E and B Fields. Since E and B Fields are available it is possible to distinguish between a forward (+k) and a backward (-k) propagating wave. So this is not just the fourier transform of different field components!
In full 3D the 6 real scalar fields (Ex, Ey, Ez, Bx, By, Bz) should be converted to 3 complex scalar k-spaces (for example k_x, k_y, k_z) for each of the 3 possible polarizations in 3D. So k_x would mean, that the EM wave is polarized along the x-Axis. Dont know if there are better naming conventions, this is just the first that came to my mind.

These routines should be placed inside the Field Analyzer class.

**Comment by skuschel** [comment]
@stetie

**Comment by skuschel** [comment]
#74

**Comment by Ablinne** [comment]
#74 was pulled, so this can be closed.
