### ISSUE TITLE
Ubuntu 14.04 fails CI tests

### ISSUE THREAD

**Issue by Ablinne** [skuschel/postpic#212]
Yet another package dropped compatibilty with Python 3.4 (pygments) which breaks the CI tests. (See https://travis-ci.org/skuschel/postpic/jobs/531754677). I propose to drop Ubuntu 14.04 from the CI test, as it is EOL.

**Comment by skuschel** [comment]
I am totally happy with dropping old support, but my experience was, that a lot of clusters use "stable" versions which happen to be rather old and ubuntu 14.04. is just an example of compatibility with older versions. Can we first confirm, that we are still testing against versions at least as old as on the bigger clusters? What do you think?

- [ ] jureca
- [ ]  GSI Kronos
- [ ]  The HZDR cluster
- [ ] Uni Jena omega

**Comment by Ablinne** [comment]
Omega cluster has been shut down anyway. Python 3.4 is already officially End-of-life (https://www.python.org/dev/peps/pep-0429/). Ubuntu 14.04 is under Extended support for paying users, but standard support ended in April (https://wiki.ubuntu.com/Releases). Python 2.7 will also be dropped by the end of this year.
The problem with the 14.04 CI test was in the documentation building step. For the meantime we can also just reduce the test for 14.04 to a fast test without the documentation.

On the other hand: On all clusters I have never bothered to use the system python installation on those old distros with Python 3.4, because it is far easier to just install anaconda and be done with it...

**Comment by Ablinne** [comment]
I have fixed the tests for 14.04 by pinning the version for `pygments`.

**Comment by skuschel** [comment]
sounds good! :+1:
