### ISSUE TITLE
`helper.kspace_propagate`: moving window does not work as expected

### ISSUE THREAD

**Issue by Ablinne** [skuschel/postpic#215]
Due to the changes made in #209, the moving window method of `kspace_propagate` does not work as intended. This also affects the `time_profile_at_plane` function. Already working on the fix...

**Comment by stetie** [comment]
I can confirm that this fix works for me :+1:

**Comment by Ablinne** [comment]
I have now also added the fix for `time_profile_at_plane`, but i have not tested it beyond the automated tests, yet.

**Comment by Ablinne** [comment]
I have fixed `time_profile_at_plane` now in the updated Pull request and confirmed that it works as intended.

**Comment by Ablinne** [comment]
fixed via #216
