### ISSUE TITLE
createField ValueError 'Passed array grid_node is not monotonous'

### ISSUE THREAD

**Issue by hollatz** [skuschel/postpic#233]
I am using this version of postpic
```python
import postpic as pp
print(pp.__version__)

v0.4+73.gf4fcaa1

```
I use this version of python
```python
import sys
print(sys.version)

3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609]

```

When using "createField" with a species where all particles have the same value for some property, for example plasma electrons having zero initial kinetic energy on first dump, a ValueError will be raised and the program stops rather then skipping or making an exception for this dump.

example code ('0000.sdf' is an epoch dump containing 'electrons' that where loaded without initial velocity):

```python
import postpic as pp
from postpic import MultiSpecies as MS
pp.chooseCode('epoch')
my_dump=pp.readDump('0000.sdf')
electron_analyser = MS(my_dump, 'electron')
electron_energy = electron_analyser.createField('Ekin','y_um')

ValueError                                Traceback (most recent call last)
<ipython-input-3-6e157415f0b1> in <module>()
      4 my_dump=pp.readDump('0000.sdf')
      5 electron_analyser = MS(my_dump, 'electron')
----> 6 electron_energy = electron_analyser.createField('Ekin','y_um')

ValueError: Passed array grid_node is not monotonous.

```

**Comment by skuschel** [comment]
I dont know your setup, but I the problem here seems to be, that ALL your particles have identical `Ekin`. Therefore postpic fail to calculate proper bounds for the plot. I know the error message is highly uninstructive. You can try proving the bounds manually using `rangex=...` or `rangey=...` kwarg. However, is that actually a useful plot, since all `Ekin` are zero?
Can you please try `rangex`? Also, using a later dump should solve the problem as soon as the `Ekin` span over a range. Does that fix your problem?

**Comment by hollatz** [comment]
You are right, all the Ekin are zero, and this is also not physical and in this particular case not interesting to look at. I fixed it by giving an initial temperature to the electrons.

However this is more like a convenience thing. After my simulation i just wanted to look at the time evolution of certain properties through the whole simulation, for example the electron energy in case of an LWFA sim, so i plot the energy for every dump. Then the Error is raised and i need to redo the sim or manually exclude all dumps where this is an issue. Just convenience.

**Comment by skuschel** [comment]
Yeah, I agree its not convenient. The easiest way around is probably if you wrap your code in
```python
try:
    electron_energy = electron_analyser.createField('Ekin','y_um')
except(ValueError):
    electron_energy = None
    # or do whatever you need to do without a plot, probably  a `continue` if its within a loop 
```

These border cases are difficult  to handle, as they may cause other trouble depending on what you do with them later. I rather keep the error on the first point of occurrence, as the field is not what you would expect. If anyone can think of a better way, I am happy to change this.

**Comment by skuschel** [comment]
TODO: Better error message
