### ISSUE TITLE
Reading png files fails for newer scipys

### ISSUE THREAD

**Issue by Ablinne** [skuschel/postpic#241]
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-6434a725eedb> in <module>()
----> 1 img = pp.Field.importfrom('PointingScreenReferenzNachAnbringenKalibrierungsfolie_KameraBIldausschnitt_verschoben.png')

/raid/home/albn/Physik/PostPic/postpic/postpic/datahandling.py in importfrom(cls, filename, **kwargs)
    587     @helper.append_doc_of(io.import_field)
    588     def importfrom(cls, filename, **kwargs):
--> 589         return io.import_field(filename, **kwargs)
    590 
    591     def __init__(self, matrix, name='', unit='', **kwargs):

/raid/home/albn/Physik/PostPic/postpic/postpic/io/__init__.py in import_field(filename, **kwargs)
     55         # assume anything else, this will open png files with pypng and all other files
     56         # with pillow
---> 57         return _import_field_image(filename, **kwargs)
     58 
     59 

/raid/home/albn/Physik/PostPic/postpic/postpic/io/image.py in _import_field_image(filename, hotpixelremove)
     32     from ..datahandling import Field, Axis
     33     if filename.lower().endswith('png'):
---> 34         data = _readpng(filename)
     35     else:
     36         data = _read_image_pil(filename)

/raid/home/albn/Physik/PostPic/postpic/postpic/io/image.py in _readpng(filename)
     84     meta = png.Reader(filename)
     85     meta.preamble()
---> 86     ret = sm.imread(filename)
     87     if meta.sbit is not None:
     88         significant_bits = ord(meta.sbit)

AttributeError: module 'scipy.misc' has no attribute 'imread'
```

Newer Scipy versions do not have `scipy.misc.imread`.

**Comment by Ablinne** [comment]
I have a workaround at my fork: https://github.com/Ablinne/postpic/tree/ab/add_png_fallback

**Comment by skuschel** [comment]
The whole point of the exercise was to keep the count values in the pngs untouched. I remember that particularly on LabView written pngs from 10, 12 and 16 bit cameras, it was difficult to get the count values right and the PIL didnt do a good job either -- at least a few years ago. Scipy suggests to use `imageio.imread` instead. Seem like a proper testing job with various pngs...

https://docs.scipy.org/doc/scipy-1.2.1/reference/generated/scipy.misc.imread.html
https://imageio.readthedocs.io/en/stable/userapi.html

**Comment by Ablinne** [comment]
Just replacing `scipy.imread` by `imageio.imread` works fine on a 12-bit image from LabView that I have handy right now. Both methods rely on PIL to actually read the image data. However, 12 bit PNGs are stored upscaled to 16 bit and neither of these methods revert the upscaling, which our own `_readpng` function does. Unfortunately neither PIL or imageio offer a way of accessing the bit depth metadata field. This is why we need the `png` package (pypng).
I think we should reorganize the imagereader like this:
* If PNG image is read, test for `png` package. If that is not present, issue a warning but continue by opening the image using the generic image opening method anyway (instead of failing with ImportError as it is now).
* In either case, to load the actual image data, try imageio first and fallback to PIL if imageio is not installed.
