### ISSUE TITLE
pa('Ekin_MeV') gives incorrect values

### ISSUE THREAD

**Issue by zubairy** [skuschel/postpic#260]
- postpic `v0.4+148.g8f84692`
- python `3.7.6 (default, Jan  8 2020, 19:59:22) \n[GCC 7.3.0]`
- code `epoch`

I processed particles kinetic energy using `MultiSpecies`, however, `pa('Ekin_MeV')` gives incorrect values, as shown by the following picture (the 2nd value of Ekin, for example):

![image](https://user-images.githubusercontent.com/12051096/108824046-3701b800-75fc-11eb-892d-20b5084d7ecf.png)

Has tested for SDF data at other timesteps. It seems that all `Ekin_MeV/keV[_qm/amu]` fails to give the correct value except the first particle. If convenient, could you kindly see if you can reproduce this issue and find why it happens?

Regards

**Comment by skuschel** [comment]
Hi zubairy, thanks for opening the issue. I will look into it!

**Comment by skuschel** [comment]
Hi Zubairy,
I tried to reproduce the issue, but everything worked. I am attaching the jupyter notebook I used for the test. Can you please run it an compare the results?


[Issue260 Particle Issue.zip](https://github.com/skuschel/postpic/files/6029099/Issue260.Particle.Issue.zip)

**Comment by zubairy** [comment]
Hi Stephan,

Thank you very much for your quick response! I don't have a proper Jupyter Notebook enviorment, so I downloaded the sample data and test it on the linux cluster where this issue happens. The test log is as follows: 

```
[lgzhang@mu01 hdf5]$ ls
data00000100.h5  data00000200.h5  data00000300.h5  data00000400.h5  data00000500.h5
[lgzhang@mu01 hdf5]$ python
Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import postpic as pp
>>> pp.__version__
'v0.4+148.g8f84692'
>>> pp.chooseCode('openpmd')
>>> sr = pp.readSim('*.h5')
>>> len(sr)
5
>>> sr[0].listSpecies()
['electrons', 'ions']
>>> ms = pp.MultiSpecies(sr[0], 'electrons')
>>> ms
<MultiSpecies including all "electrons" (19600)>
>>> ms('Ekin')
array([5.83786150e-22, 5.72630300e-22, 5.19477845e-21, ...,
       2.06164143e-26, 3.68200166e-27, 2.11229469e-27])
>>> ms('Ekin_MeV')
array([3.64370655e-009, 2.46007748e+282, 1.11429365e+283, ...,
       3.69275107e+289,             inf,             inf])
>>> ms('Ekin')/ms('elementary_charge')/1e6
array([3.64370655e-09, 3.57407721e-09, 3.24232569e-08, ...,
       1.28677537e-13, 2.29812468e-14, 1.31839065e-14])
>>> ms('gamma_m1') * 0.511
array([3.64371435e-09, 3.57408487e-09, 3.24233263e-08, ...,
       1.28677812e-13, 2.29812960e-14, 1.31839347e-14])
>>>
```

Also I tested on my wsl (windows subsystem for linux) enviorment, this time the code works well :joy: (log attached below). This makes me believe that most likely something is wrong with my environment but not the code, though I have no idea where the problem is for now. I need more test on the linux cluster. It will be great help if you have some thoughts.

Best wishes!

Lingang

```
lgzhang@LGZHANG-PC:/mnt/e/git/lgzhang0402/wsl$ ls
example-2d  example-2d.tar.gz
lgzhang@LGZHANG-PC:/mnt/e/git/lgzhang0402/wsl$ python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import postpic as pp
>>> pp.__version__
'v0.4+148.g8f84692'
>>> pp.chooseCode('openpmd')
>>> sr = pp.readSim('example-2d/hdf5/*.h5')
>>> len(sr)
5   
>>> sr[0].listSpecies()
['electrons', 'ions']
>>> ms = pp.MultiSpecies(sr[0], 'electrons')
>>> ms
<MultiSpecies including all "electrons" (19600)>
>>> ms('Ekin')
array([5.83786150e-22, 5.72630300e-22, 5.19477845e-21, ...,
       2.06164143e-26, 3.68200166e-27, 2.11229469e-27])    
>>> ms('Ekin_MeV')
array([3.64370655e-09, 3.57407721e-09, 3.24232569e-08, ...,
       1.28677537e-13, 2.29812468e-14, 1.31839065e-14])    
>>> ms('Ekin')/ms('elementary_charge')/1e6
array([3.64370655e-09, 3.57407721e-09, 3.24232569e-08, ...,
       1.28677537e-13, 2.29812468e-14, 1.31839065e-14])
```

**Comment by skuschel** [comment]
Hi Lingang,

The fact that the first entry is right, but all others are wrong puzzles me very much. I cannot image how this can happen. I would try a few things:
* Numpy comes with tests. Run them to see if numpy works correctly. It's only a "numpy.test()",  I believe.
* As the data is correctly read from disk, maybe check the value and type of the elementary charge in postpic. Also check the source: postpic is getting this value from scipy.constants.

Other than that it's hard to think what may cause this. Please keep me posted on your progress. This actually turns into a very interesting python problem!  ;)

I looking forward to hear, if the numpy tests are working.

Cheers
Stephan

**Comment by zubairy** [comment]
Hi Stephan, hope I've provided useful testing results. This problem really very strange, but anyway, `Ekin` is correct and does not affect the use of `postpic`.

- cluster `mu01`, gives wrong `Ekin_MeV` values. The `elementary_charge` seems resonable in both `postpic` and `scipy`. 

    ```
    >>> ms
    <MultiSpecies including all "electrons" (19600)>
    >>> ms('Ekin')
    array([5.83786150e-22, 5.72630300e-22, 5.19477845e-21, ...,
    	2.06164143e-26, 3.68200166e-27, 2.11229469e-27])
    >>> ms('Ekin_MeV')
    array([3.64370655e-009, 2.43819327e+282, 1.10826922e+283, ...,
    				inf,             inf,             inf])
    >>> ms('elementary_charge')
    array([1.60217663e-19, 1.60217663e-19, 1.60217663e-19, ...,
    	1.60217663e-19, 1.60217663e-19, 1.60217663e-19])
    >>> type(ms('elementary_charge'))
    <class 'numpy.ndarray'>
    >>> type(ms('elementary_charge')[2])
    <class 'numpy.float64'>
    >>> type(ms('elementary_charge')[1])
    <class 'numpy.float64'>
    >>> type(ms('elementary_charge')[0])
    <class 'numpy.float64'>
    >>> scipy.constants.elementary_charge
    1.602176634e-19
    >>> type(_)
    <class 'float'>
    ```

- The `numpy.test()` logs in `mu01` and `wsl` (the normal one) are attached here.
    [cluster_log1.log](https://github.com/skuschel/postpic/files/6033000/cluster_log1.log)
    [cluster_log2.log](https://github.com/skuschel/postpic/files/6033001/cluster_log2.log)
    [wsl_log1.log](https://github.com/skuschel/postpic/files/6033038/wsl_log1.log)
    [wsl_log2.log](https://github.com/skuschel/postpic/files/6033039/wsl_log2.log)

**Comment by skuschel** [comment]
Hi Lingang,
I am not an expert on the internals of numpy, but it seems to me that some of your tests are actually failing. The ones marked with 'xfail' are ok to fail. I ran the tests on my laptop, here is the output for what I believe it should look like.
[numpytest.log](https://github.com/skuschel/postpic/files/6035739/numpytest.log)

I am sorry I cannot help you further with this. I would probably reinstall python and try to fix numpy first, but I dont know if there is better way. Its very strange. 
Cheers
Stephan

**Comment by zubairy** [comment]
Hi Stephan,

After newly installed python3.8 anaconda3, there still has the problem [sigh]. I use `Ekin` for now and maybe come to feedback later on if I find the reason. Thanks for your patient help.

Regards
Lingang

**Comment by skuschel** [comment]
Hi Lingang,

of course! This is the worst kind of bug as it can go undetected -- you just getting false values, but no error. So if there is anything I can add to postpic to detect this isssue in the future, that would be very interested! 
The issue could also be related to the underlying data reader. Can you please add which epoch version  and which SDF version you are using? 
If you send me your simulation dump and a part of your code, I can offer to run it on my machine to see if I can reproduce it here.
Cheers
Stephan
