### ISSUE TITLE
add test cases for operator overloading of MultiSpecies Object

### ISSUE THREAD

**Issue by skuschel** [skuschel/postpic#33]

**Comment by skuschel** [comment]
Is this solved by #128 as well?

**Comment by Ablinne** [comment]
Operators of `MultiSpecies` are independent of Field. `MultiSpecies` has only `__add__` and `__iadd__` for "adding" particles. Returned histograms are `Field`s and are covered by #128.

**Comment by skuschel** [comment]
my bad. sorry!
