### ISSUE TITLE
EPOCH reader: listSpecies() truncates species names with a dash (-)

### ISSUE THREAD

**Issue by stetie** [skuschel/postpic#58]
If there are multiple species defined in the epoch input.deck file with names like 'C6-1', 'C6-2', 'C6-3' (in my case for different types of C6), then the name gets truncated by postpic's listSpecies() function to 'C6'. In turn, it is not possible to use the output of listSpecies() to plot e.g. the number density of all species:

``` python
pas = [MS(dr, s) for s in dr.listSpecies()]
for pa in pas:
        nd = pa.createField(MS.X, MS.Y, optargsh=optargsh,simextent=True)
```

raises the error
`KeyError: 'Grid/Particles/C6'`
as the keys are (correctly) named Grid/Particles/C6-1, Grid/Particles/C6-2, etc.
I think the error might by in [this line](https://github.com/skuschel/postpic/blob/master/postpic/datareader/epochsdf.py#L142)

**Comment by skuschel** [comment]
Yepp, I always use `c6a`, `c6b`, and so on. Particularly because I did not find which special characters are allowed for species names by EPOCH.

You are right about the position. The regex need to be adjusted to match special characters as well.

**Comment by skuschel** [comment]
Do you want to change it to your need? I am not sure what special characters are allowed in epochs naming conventions...

**Comment by stetie** [comment]
It's fine for me to change to species names in the future, however there should be some documentation about the supported naming conventions.
