### ISSUE TITLE
identifyspecies() does not recognize 'Proton'

### ISSUE THREAD

**Issue by stetie** [skuschel/postpic#59]
I have a species called 'Proton', which contains - obviously - protons. When I try to create a new field like

``` python
ekin = pa.createField(MS.X, MS.Y, weights=MS.Ekin_MeV, optargsh=optargsh, simextent=True)
```

it invokes the `identifypsecies()` function, which fails with the following error:

```
[...]/postpic/postpic/helper.py in identifyspecies(cls, species)
    180         if regexdict['elem']:
    181             ret['mass'] = float(cls._masslistelement[regexdict['elem']]) * \
--> 182                 1836.2 * cls.me
    183             if regexdict['elem_c'] == '':
    184                 ret['charge'] = 0

KeyError: 'Pr'
```

It seems like `identifypsecies()` doesn't know Protons and it also doesn't give meaningful error messages.

**Comment by stetie** [comment]
Oh, and how do I convince postpic to just use the mass and charge dumped along with the simulation and skip the identifyspecies()?

**Comment by stetie** [comment]
I used an outdated version of postpic. Now it apparently reads mass and charge from the dump. Still, `identifyspecies()` should be able to identify protons.

**Comment by skuschel** [comment]
Thanks for pointing this out! I think it does identify `proton` (lower case) correctly. The routines for the trivial names need to be rewritten anyways. I didnt want to compare lowercase string by default because it can get tricky with element symbols.
