### ISSUE TITLE
Color scale of weights doesn't show the right values

### ISSUE THREAD

**Issue by stetie** [skuschel/postpic#60]
I'm plotting the following for a TNSA simulation
```python
ekin = pa.createField(MS.X, MS.Y, weights=MS.Ekin_MeV, optargsh=optargsh, simextent=True)
plotter.plotField(ekin, xlim=[-0.5*1e-5, 1.0*1e-5], log10plot=False)
```
In the final plot, the colorbar shows a range from -2e28 to 2e28. From another plot,
```python
EkinvsX = pa.createField(MS.X, MS.Ekin_MeV, optargsh=optargsh, simextent=True)
plotter.plotField(EkinvsX, xlim=[-0.5*1e-5, 1.0*1e-5])
```
I know that the maximum kinetic energy in this simulation is about 15 MeV, which is much more reasonable. How do I get a correct color scale?

**Comment by skuschel** [comment]
Well what you are actually doing is summing up the **total** kinetic energy on grid in MeV. What you probably want is the **average** kinetic energy on grid:
```python
ekintot = pa.createField(MS.X, MS.Y, weights=MS.Ekin_MeV, optargsh=optargsh, simextent=True)
nd = pa.createField(MS.X, MS.Y, optargsh=optargsh, simextent=True)
plotter.plotField(ekintot/nd, xlim=[-0.5*1e-5, 1.0*1e-5], log10plot=False)
```
OR you might be looking for the spectrum:
```python
spec = pa.createField(Ekin_MeV, optargsh=optargsh)
plotter.plotField(spec, log10plot=False)
```
I hope this helps! :)

**Comment by stetie** [comment]
Thanks, it's the first one I was looking for :-) Is there a way to make the colorbar start at 0, even for non-log10 plots? I can set `clim=[0, 20]`, but it will still make the value range start from -20.

**Comment by skuschel** [comment]
That seems like a bug in the plotter. Please try again with the current `dev` branch:
`pip install --user git+https://github.com/skuschel/postpic.git@dev`

**Comment by stetie** [comment]
Thanks, the fix in the dev branch works perfectly :)

**Comment by skuschel** [comment]
pushed to master, aea1fea
