### ISSUE TITLE
savecsv option for plotField() broken

### ISSUE THREAD

**Issue by stetie** [skuschel/postpic#61]
If I set the option `savecsv=True` when calling `plotField()`, either of this happens:
- If it is a 2d plot, nothing happens.
- If it is a 1d plot, I get the following error:

``` python
postpic/postpic/plotting/plotter_matplotlib.py in plotFields1d(self, *fields, **kwargs)
    325         ax = fig.add_subplot(1, 1, 1)
    326         name = kwargs.pop('name', fields[0].name)
--> 327         MatplotlibPlotter.addFields1d(ax, *fields, **kwargs)
    328         self._plotfinalize(fig)
    329         self.annotate(fig, project=self.project)

/home_4TB/stietze/postpic/postpic/plotting/plotter_matplotlib.py in addFields1d(ax, *fields, **kwargs)
    234             if clearinfos:
    235                 field.infos = []
--> 236             MatplotlibPlotter.addField1d(ax, field, **kwargs)
    237         MatplotlibPlotter.annotate_fromfield(ax, field)
    238         MatplotlibPlotter.annotate(ax, infostring=str(infostrings))

TypeError: addField1d() got an unexpected keyword argument 'savecsv'
```

In either case, no csv file is written.

**Comment by skuschel** [comment]
Where did you find this is an valid option? There is `Field.exporttocsv(self, filename)`. That function should just do what you are looking for.

**Comment by stetie** [comment]
In [here](https://github.com/skuschel/postpic/blob/dev/postpic/plotting/plotter_matplotlib.py#L272) and [here](https://github.com/skuschel/postpic/blob/dev/postpic/plotting/plotter_matplotlib.py#L336). But I don't need the feature right now, so this isn't urgent.

**Comment by skuschel** [comment]
oh yes, that will need to be removed

**Comment by skuschel** [comment]
Obsolete due to #130 ?

**Comment by stetie** [comment]
Yes, it's obsolete.
