### ISSUE TITLE
contourlevels option does not work

### ISSUE THREAD

**Issue by stetie** [skuschel/postpic#63]
When I try to use the `contourlevels` option for a 2D plot, I get the error that an numpy array is not callable. 
## Solution

Change [this line](https://github.com/skuschel/postpic/blob/dev/postpic/plotting/plotter_matplotlib.py#L303) from 

``` python
extent=field.extent())
```

to

``` python
extent=field.extent)
```

**Comment by skuschel** [comment]
At some point it might be better to just rewrite the plotting routines completely to increase compatibility with jupyter as well. However, since you spottet the change -- do you want to put in a pull request?
