### ISSUE TITLE
Operator overloading for axis objects

### ISSUE THREAD

**Issue by stetie** [skuschel/postpic#94]
Rescaling of axis currently requires something like this:
```python
ax = kspace.axes[1]
ax.setextent(np.array(ax.extent)*800e-9/6.3, len(ax))
```
Maybe replace this by overloading of operators for axis object?

**Comment by skuschel** [comment]
In principle `Field.transform` can already do that. However its well over the top for a simple renormalization of the axis and also the regriding should be avoided. Here is a new idea, just for discussion:

* rename `Field.transform` to `Field.map_coordinates`
* The new function `Field.transform` uses `map_coordinates` but also includes the jacobian of the transformation. That means that `transform` must conserve the integral.
* The new functions `Field.map_axis_coordinates` and `Field.transform_axis` act accordingly, but only on the coordinates of a single axis. That means, that `map_axis_coordinates` does not touch the data matrix at all. If the transformation is non-linear, this might however transform the equally spaced grid into a non-equally spaced grid. But thats totally fine I think.
* Same game here: the `transform` version does the same but also takes care for the correct jacobian.

Stefans Problem would then write `kspace2 = kspace.transform_axis_coordinates('y', lambda y: y*800e-9/(2*pi))`

I only identify one possible issue with this solution:
*  `Field.transform` expects the transformation from final coordinates to source coordinates.
*  `Field.transform_axis` expects the transformation from source coordinates to final coordinates.
That seems unnecessary confusing to me.

**Comment by skuschel** [comment]
One more iteration: As soon as the `transform_*` functions are there, why would anyone still used the `map_*` functions at all as they are ignoring the jacobian? I do not see a good reason for that. Maybe they should all just be called `map_*` and the ones ignoring the jacobian can become hidden (`_map_*`).

An alternative to `map` maybe `geometric_transform`, but `map` seems short and still to the point to me.

**Comment by Ablinne** [comment]
Stefan could already just write:

    ax.grid = ax.grid * 800e-7 / 2 / np.pi

seems simple enough for me...

**Comment by skuschel** [comment]
Ah right, `ax.grid` has a setter! Yepp that is nice for rescaling. However, it breaks the integral.

**Comment by stetie** [comment]
Thanks! That's exactly what I was looking for.

**Comment by Ablinne** [comment]
Even though my commend of Oct 6 is invalidated because Axis objects are immutable now, I think the presence of Field.map_axis_grid and Field.map_coordinates is enough to close this.
