### ISSUE TITLE
Easy way to set colormap

### ISSUE THREAD

**Issue by stetie** [skuschel/postpic#95]
When plotting, postpic always uses the predefined colormaps `jet` and `MatplotlibPlotter.symmap`. To manually change the colormap, I have to use a command like
```python
p = plotter.plotField(nd, log10plot=False)
p.axes[0].images[0].set_cmap('viridis')
```
I would like to have a `cmap` keyword for the `plotField()` function. If I understood the code correctly, the only change necessary would be in
https://github.com/skuschel/postpic/blob/ef103a8c1f665042c37246d456412ba18ac8aa72/postpic/plotting/plotter_matplotlib.py#L272
`addField2d()` would have to take a `cmap=` argument and pass it to `imshow()`. If no `cmap=` keyword is given, the default colormaps should be used.

**Comment by Ablinne** [comment]
Short term answer: we can just add the keyword argument, improves usability at little cost.

Long-term answer: According to @skuschel, the plotter class is just a hack. It is not very extensible and should be completely rewritten.
